/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Tue Jul 14 17:42:08 GMT 2026
 */

package org.apache.openjpa.trader.client;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class LoginDialog_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.apache.openjpa.trader.client.LoginDialog"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    /*No java.lang.System property to set*/
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(LoginDialog_ESTest_scaffolding.class.getClassLoader() ,
      "com.google.gwt.user.client.Element",
      "com.google.gwt.i18n.client.HasDirection",
      "com.google.gwt.user.client.ui.HasAnimation",
      "com.google.gwt.core.client.GWT$UncaughtExceptionHandler",
      "com.google.gwt.user.client.ui.SourcesTableEvents",
      "com.google.gwt.user.client.ui.FlexTable",
      "com.google.gwt.user.client.Event",
      "com.google.gwt.event.dom.client.HasKeyUpHandlers",
      "com.google.gwt.user.client.ui.TextBox",
      "com.google.gwt.user.client.ui.PopupPanel$PositionCallback",
      "com.google.gwt.user.client.ui.HTML",
      "com.google.gwt.event.dom.client.DomEvent$Type",
      "com.google.gwt.event.dom.client.HasAllKeyHandlers",
      "com.google.gwt.user.client.ui.Focusable",
      "com.google.gwt.user.client.EventPreview",
      "com.google.gwt.user.client.ui.UIObject",
      "com.google.gwt.user.client.ui.Label",
      "com.google.gwt.event.shared.EventHandler",
      "com.google.gwt.user.client.ui.HasWordWrap",
      "com.google.gwt.user.client.ui.UIObject$DebugIdImpl",
      "com.google.gwt.user.client.ui.SimplePanel",
      "com.google.gwt.user.client.ui.SourcesPopupEvents",
      "com.google.gwt.user.client.ui.SourcesChangeEvents",
      "com.google.gwt.event.dom.client.HasMouseOverHandlers",
      "com.google.gwt.dom.client.DivElement",
      "com.google.gwt.user.client.ui.TextBoxBase",
      "com.google.gwt.event.dom.client.HasMouseUpHandlers",
      "com.google.gwt.user.client.Event$NativePreviewHandler",
      "com.google.gwt.event.dom.client.HasClickHandlers",
      "com.google.gwt.event.dom.client.HasAllFocusHandlers",
      "com.google.gwt.user.client.ui.Widget",
      "com.google.gwt.user.client.ui.HasText",
      "org.apache.openjpa.trader.client.LoginDialog",
      "com.google.gwt.dom.client.Element",
      "com.google.gwt.user.client.ui.SourcesFocusEvents",
      "com.google.gwt.user.client.ui.HasFocus",
      "com.google.gwt.event.logical.shared.ValueChangeHandler",
      "com.google.gwt.event.dom.client.HasMouseDownHandlers",
      "com.google.gwt.user.client.EventListener",
      "com.google.gwt.user.client.ui.HasWidgets",
      "com.google.gwt.event.dom.client.HasAllMouseHandlers",
      "com.google.gwt.user.client.ui.HasValue",
      "com.google.gwt.dom.client.EventTarget",
      "com.google.gwt.event.dom.client.HasMouseWheelHandlers",
      "com.google.gwt.event.dom.client.HasChangeHandlers",
      "com.google.gwt.core.client.GWT",
      "com.google.gwt.user.client.ui.Panel",
      "com.google.gwt.dom.client.NativeEvent",
      "com.google.gwt.event.logical.shared.HasValueChangeHandlers",
      "com.google.gwt.event.dom.client.ClickHandler",
      "com.google.gwt.event.dom.client.HasMouseOutHandlers",
      "com.google.gwt.event.dom.client.HasFocusHandlers",
      "com.google.gwt.event.shared.GwtEvent$Type",
      "com.google.gwt.user.client.ui.FocusWidget",
      "com.google.gwt.user.client.ui.HasName",
      "com.google.gwt.event.shared.HasHandlers",
      "com.google.gwt.user.client.ui.HasHTML",
      "com.google.gwt.event.dom.client.HasKeyDownHandlers",
      "com.google.gwt.user.client.ui.Button",
      "com.google.gwt.event.dom.client.HasMouseMoveHandlers",
      "com.google.gwt.user.client.ui.HasHorizontalAlignment",
      "com.google.gwt.core.client.JavaScriptObject",
      "com.google.gwt.user.client.ui.ButtonBase",
      "com.google.gwt.event.logical.shared.ResizeHandler",
      "com.google.gwt.event.dom.client.HasKeyPressHandlers",
      "com.google.gwt.user.client.ui.PopupPanel",
      "com.google.gwt.user.client.ui.SourcesClickEvents",
      "com.google.gwt.user.client.ui.SourcesKeyboardEvents",
      "com.google.gwt.event.logical.shared.HasCloseHandlers",
      "com.google.gwt.user.client.ui.HTMLTable",
      "com.google.gwt.event.dom.client.HasBlurHandlers",
      "com.google.gwt.dom.client.Node",
      "com.google.gwt.user.client.ui.SourcesMouseEvents"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(LoginDialog_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.google.gwt.core.client.GWT",
      "com.google.gwt.user.client.ui.UIObject"
    );
  }
}
